events {
    worker_connections 1024;  # Adjust worker connections as needed
}

http {
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        # Enable the NGINX status page for the exporter
        location /nginx_status {
            stub_status on;
            access_log off;
            allow all;  # Temporarily allow all sources
        }
    }
}
